# Site settings
title: Daily Thoughts
description: Collection of ideas, thoughts and rambles that come out of my head every day
url: https://blog.alessiosignorini.com
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
permalink: /post/:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Collections
collections:
  posts:
    output: true
    permalink: /:title/
  recipes:
    output: true
    permalink: /recipes/:title/
  travel:
    output: true
    permalink: /travel/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "travel"
    values:
      layout: "travel"

# Exclude
exclude:
  - .devcontainer
  - .git
  - Gemfile
  - Gemfile.lock
  - README.md
