# Site settings
title: The title
description: Some description about the blog
url: https://blog.yourdomain.com
baseurl: ""

# Google Analytics
google_analytics: ""

# If only one category is to be shown, set it here
show_only: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

permalink: /:title/

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude
exclude:
  - .devcontainer
  - .git
  - Gemfile
  - Gemfile.lock
  - README.md
